name: rust-demo
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set up Env
        run: export PRINT_ENV=Dev ENDPOINT=srv+mongodb://nongkai.com PORT=5000
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test
      - name: Deploy
        run: echo "Deploying to production"
    
