name: learn-github-actions
run-name: ${{ github.actor}} is learning GitHub Actions
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: demo-rust

on:
  push:
    branches:
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. เช็คเอาต์โค้ดจากรีโป
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: $DOCKER_USERNAME # ใช้ Secrets เก็บชื่อผู้ใช้
        password: $DOCKER_PASSWORD # ใช้ Secrets เก็บรหัสผ่าน

    # 3. Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }} .

    # 4. Push Docker Image
    - name: Push Docker Image
      run: |
        docker push $DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }}
    
